### ISSUE TITLE
E-commerce framework explorations

### ISSUE THREAD

**Issue by Dogacel** [Dogacel/Kalas-Iris#36]
- [ X] Search for different e-commerce frameworks
- [Wix](https://www.wix.com/ecommerce/website) - @Dogacel 
- [NopCommerce](https://www.nopcommerce.com/en) - @olcayakman 
- [Shopify](https://www.shopify.com/) - @zeynepkorkunc 
- [WooCommerce](https://woocommerce.com/) - @AtaAtasoy 

- [ ] Setup different e-commerce frameworks ( Hosted is more prefered )
- [ ] Try inventory management systems
- [ X] Investigate how we can implement Kalas-Iris into their website

**Comment by AtaAtasoy** [comment]
It seems that its not possible to create a free-tier website using nopcommerce. I came across this, at the last step of the get-started guide. 

![WhatsApp Image 2021-02-02 at 20 32 19](https://user-images.githubusercontent.com/40474912/106639895-7fe2c580-6596-11eb-8865-84cfee74337c.jpeg)

**Comment by AtaAtasoy** [comment]
You can review my findings about WooCommerce [here](https://github.com/Dogacel/Kalas-Iris/blob/woocommerce-docs/docs/woocommerce.md).
