### ISSUE TITLE
Find example shop database

### ISSUE THREAD

**Issue by Dogacel** [Dogacel/Kalas-Iris#38]

**Comment by AtaAtasoy** [comment]
[Example dataset](https://data.world/jfreex/products-catalog-from-newchiccom) 

With Columns 

* category
* subcategory
* name
* current_price
* raw_price
* currency
* discount
* likes_count
* is_new
* brand
* brand_url
* codcountry
* variation_0_color
* variation_1_color
* variation_0_thumbnail
* variation_0_image
* variation_1_thumbnail
* variation_1_image
* image_url
* url
* id
* model

**Comment by AtaAtasoy** [comment]
[Another example dataset](https://www.kaggle.com/PromptCloudHQ/flipkart-products)

This dataset has following fields:

* product_url
* product_name
* productcategorytree
* pid
* retail_price
* discounted_price
* image
* isFKAdvantage_product
* description
* product_rating
* overall_rating
* brand
* product_specifications


The category is given as a tree, such as ["Clothing >> Women's Clothing >> Lingerie, Sleep & Swimwear >> Shorts >> Alisha Shorts >> Alisha So...], the dataset doesn't contain only fashion items, but maybe with some NLP, we could be able to extract the rows which are fashion products.

**Comment by AtaAtasoy** [comment]
[Another example dataset](http://jmcauley.ucsd.edu/data/amazon/links.html) 

It contains
<img width="728" alt="Screen Shot 2021-02-12 at 11 46 04" src="https://user-images.githubusercontent.com/40474912/107747056-e5b61680-6d27-11eb-897b-4b1a961a4ea1.png">

[Link to download clothing, shoes and jewelry](http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/meta_Clothing_Shoes_and_Jewelry.json.gz)

This dataset would also require us to extract the Clothing items.

**Comment by olcayakman** [comment]
[Here](https://www.kaggle.com/jmmvutu/summer-products-and-sales-in-ecommerce-wish?select=unique-categories.csv) there is a .csv dataset called unique-categories.csv which might be useful for our purposes
